# https://docs.stirlingpdf.com/Installation/Docker%20Install
services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest-ultra-lite
    container_name: stirling-pdf
    environment:
      - DISABLE_ADDITIONAL_FEATURES=true # Disables some stuff like logins and all that
      - LANGS=en_US
    ports:
      - '8181:8080'
    volumes:
      - $DOCKER_DIR/stirlingpdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - $DOCKER_DIR/stirlingpdf/extraConfigs:/configs
      - $DOCKER_DIR/stirlingpdf/customFiles:/customFiles/
      - $DOCKER_DIR/stirlingpdf/logs:/logs/
      - $DOCKER_DIR/stirlingpdf/pipeline:/pipeline/
    restart: unless-stopped
