services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    environment:
      - TZ=$TZ
      - ADDRESS=$ADDRESS
      - TAILNET=$TAILNET
      - JELLYSEERR_API_KEY=$JELLYSEERR_API_KEY
      - LOCATION=$LOCATION

  # Glance agent for resource monitoring
  glance-agent:
    container_name: glance-agent
    image: glanceapp/agent
    volumes:
      # Add your mount points below in the format host_path:container_path with :ro suffix for read-only
      - /storage:/storage:ro
    ports:
      - 27973:27973