services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=$TZ
    ports:
      - 5055:5055
    volumes:
      - $DOCKER_DIR/jellyseerr:/app/config
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr-rtr.rule=Host(`jellyseerr.$DOMAIN_NAME`)"
      # Middlewares
      - "traefik.http.routers.jellyseerr-rtr.middlewares=middleware-oauth@file"
      # Service
      - "traefik.http.routers.jellyseerr-rtr.service=jellyseerr-svc"
      - "traefik.http.services.jellyseerr-svc.loadbalancer.server.port=5055"
