services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - $DOCKER_DIR/jellyfin/config:/config
      - $DOCKER_DIR/jellyfin/cache:/cache
      - $MEDIA_DIR/anime:$MEDIA_DIR/anime
      - $MEDIA_DIR/anime-movies:$MEDIA_DIR/anime-movies
      - $MEDIA_DIR/movies:$MEDIA_DIR/movies
      - $MEDIA_DIR/tvshows:$MEDIA_DIR/tvshows
      - /dev/shm:/data/transcode # Offload transcoding to RAM if there's enough RAM
    restart: 'unless-stopped'
    devices:
      - /dev/dri:/dev/dri # Graphic's hardware for transcoding
    ports:
      - 8096:8096
