- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezone: ${TZ}
        - type: weather
          location: ${LOCATION}
          units: metric
          hour-format: 24h
        - type: calendar
          first-day-of-week: sunday
        - type: twitch-channels
          channels:
            - hasanabi
            - otzdarva
            - johnny_health
            - mbtyugioh
            - deathydl

    - size: full
      widgets:
        - type: server-stats
          servers:
            - type: remote
              name: Main server
              url: http://${ADDRESS}:27973/
        - type: to-do
        - type: group
          widgets:
            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: Jellyfin
                  url: https://jellyfin.${TAILNET}/
                  icon: di:jellyfin
                - title: Jellyseerr
                  url: https://jellyseerr.${TAILNET}/
                  icon: di:jellyseerr
            - type: monitor
              cache: 1m
              title: Port connections
              sites:
                - title: Jellyfin
                  url: http://${ADDRESS}:8096/
                  icon: di:jellyfin
                - title: Jellyseerr
                  url: http://${ADDRESS}:5055/
                  icon: di:jellyseerr
                - title: qBittorrent
                  url: http://${ADDRESS}:8090/
                  icon: di:qbittorrent
                - title: Radarr - Anime
                  url: http://${ADDRESS}:7879/
                  icon: di:radarr
                - title: Radarr
                  url: http://${ADDRESS}:7878/
                  icon: di:radarr
                - title: Sonarr - Anime
                  url: http://${ADDRESS}:8989/
                  icon: di:sonarr
                - title: Sonarr - TV
                  url: http://${ADDRESS}:8990/
                  icon: di:sonarr
                - title: Prowlarr
                  url: http://${ADDRESS}:9696/
                  icon: di:prowlarr
                - title: Bazarr
                  url: http://${ADDRESS}:6767/
                  icon: di:bazarr
                - title: Cleanuparr
                  url: http://${ADDRESS}:11011/
                  icon: di:cleanuperr
                - title: Stirling PDF
                  url: http://${ADDRESS}:8181/
                  icon: di:stirling-pdf
            - type: docker-containers
              hide-by-default: false
    - size: small
      widgets:
        - $include: custom-apis/jellyseerr-requests.yml
        - $include: custom-apis/steam-discounts.yml
        - $include: custom-apis/epic-free-games.yml
